
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 15;
  public static final int STRINGLIT = 31;
  public static final int CONTINUE = 41;
  public static final int LPAREN = 24;
  public static final int INT = 8;
  public static final int MINUS = 13;
  public static final int GREATER_THAN = 18;
  public static final int RPAREN = 25;
  public static final int AND = 38;
  public static final int NOT = 37;
  public static final int SEMICOLON = 23;
  public static final int INTLIT = 29;
  public static final int CALLOUT = 42;
  public static final int OR = 39;
  public static final int COMMA = 28;
  public static final int CLASS = 2;
  public static final int PLUS = 12;
  public static final int MULTIPLY = 14;
  public static final int ASSIGN = 16;
  public static final int IF = 4;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 7;
  public static final int TRUE = 32;
  public static final int error = 1;
  public static final int NUMBER = 35;
  public static final int BREAK = 40;
  public static final int VOID = 11;
  public static final int FLOATLIT = 30;
  public static final int ERROR = 34;
  public static final int TIMES = 36;
  public static final int LBRACE = 26;
  public static final int ELSE = 5;
  public static final int WHILE = 6;
  public static final int NOT_EQUALS = 22;
  public static final int FLOAT = 10;
  public static final int RBRACE = 27;
  public static final int EQUALS_EQUALS = 21;
  public static final int FALSE = 33;
  public static final int GREATER_THAN_EQUALS = 20;
  public static final int LESS_THAN = 17;
  public static final int LESS_THAN_EQUALS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "ID",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "INT",
  "BOOLEAN",
  "FLOAT",
  "VOID",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "ASSIGN",
  "LESS_THAN",
  "GREATER_THAN",
  "LESS_THAN_EQUALS",
  "GREATER_THAN_EQUALS",
  "EQUALS_EQUALS",
  "NOT_EQUALS",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "INTLIT",
  "FLOATLIT",
  "STRINGLIT",
  "TRUE",
  "FALSE",
  "ERROR",
  "NUMBER",
  "TIMES",
  "NOT",
  "AND",
  "OR",
  "BREAK",
  "CONTINUE",
  "CALLOUT"
  };
}

