
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 22;
  public static final int LBRACKET = 15;
  public static final int EQUALS = 38;
  public static final int STRINGLIT = 24;
  public static final int CONTINUE = 55;
  public static final int LPAREN = 13;
  public static final int PRIVATE = 33;
  public static final int INT = 2;
  public static final int FOR = 36;
  public static final int MINUS = 20;
  public static final int GREATER_THAN = 11;
  public static final int STATIC = 53;
  public static final int RPAREN = 14;
  public static final int AND = 46;
  public static final int NOT = 41;
  public static final int SEMICOLON = 40;
  public static final int INTLIT = 23;
  public static final int CALLOUT = 54;
  public static final int OR = 47;
  public static final int COMMA = 19;
  public static final int CLASS = 52;
  public static final int NUM = 6;
  public static final int PLUS = 7;
  public static final int MULTIPLY = 21;
  public static final int IF = 4;
  public static final int THIS = 50;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 32;
  public static final int RETURN = 5;
  public static final int BRACE_B = 45;
  public static final int RBRACKET = 16;
  public static final int BRACE_A = 44;
  public static final int TRUE = 27;
  public static final int NEW = 48;
  public static final int error = 1;
  public static final int NULL = 49;
  public static final int BREAK = 51;
  public static final int VOID = 35;
  public static final int FLOATLIT = 25;
  public static final int LBRACE = 17;
  public static final int ELSE = 26;
  public static final int PROTECTED = 34;
  public static final int WHILE = 30;
  public static final int NOT_EQUALS = 10;
  public static final int FLOAT = 29;
  public static final int PUBLIC = 31;
  public static final int RBRACE = 18;
  public static final int EQUALS_EQUALS = 9;
  public static final int PAREN_B = 43;
  public static final int PAREN_A = 42;
  public static final int FALSE = 28;
  public static final int GREATER_THAN_EQUALS = 12;
  public static final int LESS_THAN = 37;
  public static final int LESS_THAN_EQUALS = 8;
  public static final int IDENTIFIER = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "ID",
  "IF",
  "RETURN",
  "NUM",
  "PLUS",
  "LESS_THAN_EQUALS",
  "EQUALS_EQUALS",
  "NOT_EQUALS",
  "GREATER_THAN",
  "GREATER_THAN_EQUALS",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "INTLIT",
  "STRINGLIT",
  "FLOATLIT",
  "ELSE",
  "TRUE",
  "FALSE",
  "FLOAT",
  "WHILE",
  "PUBLIC",
  "BOOLEAN",
  "PRIVATE",
  "PROTECTED",
  "VOID",
  "FOR",
  "LESS_THAN",
  "EQUALS",
  "IDENTIFIER",
  "SEMICOLON",
  "NOT",
  "PAREN_A",
  "PAREN_B",
  "BRACE_A",
  "BRACE_B",
  "AND",
  "OR",
  "NEW",
  "NULL",
  "THIS",
  "BREAK",
  "CLASS",
  "STATIC",
  "CALLOUT",
  "CONTINUE"
  };
}

